GET http://127.0.0.1:3000/api/members

###
POST http://127.0.0.1:3000/api/members
Content-Type: application/json

{
    {
    "id": 11,
    "name": "Zake",
    "team": "Engineering",
    "position": "Android Developter",
    "emailAddress": "zake@google.com",
    "phoneNumber": "010-xxxx-xxxx",
    "admissionDate": "2021/06/12",
    "birthday": "1995/09/27",
    "profileImage": "profile11.png",
  }
}
